FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

RUN npm install -g @nestjs/cli

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]